# Generated by Django 3.0.7 on 2024-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AB', 'Abierto'), ('EN', 'En Progreso'), ('CE', 'Cerrado')], default='AB', max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre_aprox', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
