# Generated by Django 3.0.7 on 2024-03-28 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidad',
            old_name='fecha_cierre_aprox',
            new_name='fecha_cierre_estimada',
        ),
        migrations.RemoveField(
            model_name='oportunidad',
            name='estado',
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Producto'),
        ),
    ]
