# Generated by Django 3.0.7 on 2024-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20240327_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='correo_electronico',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='numero_telefonico',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
