# Generated by Django 3.0.7 on 2024-04-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20240403_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidad',
            name='producto',
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='productos',
            field=models.ManyToManyField(related_name='oportunidades', to='registro.Producto'),
        ),
    ]
