# Generated by Django 3.0.7 on 2024-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20240403_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='nombre',
            field=models.CharField(default='Ingrese su nombre completo', max_length=100),
        ),
    ]
