# Generated by Django 3.0.7 on 2024-04-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20240403_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='nombre',
            field=models.CharField(default='Ingrese su nombre ', max_length=100),
        ),
    ]
